# Generated by Django 5.0 on 2024-01-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_suite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sentiments_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sentence', models.TextField(max_length=200)),
                ('Sentiment', models.TextField()),
            ],
        ),
    ]
